In [6]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib as pyplot
import pickle
from matplotlib import style
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
import seaborn as sns
from sklearn.utils import shuffle
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('student-mat.csv', sep=";")

In [8]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [9]:
# show corelation matrix
plt.figure(figsize=(10,10))
sns.heatmap(df.corr(),annot=True,cmap='coolwarm')
plt.show()

ValueError: could not convert string to float: 'GP'

In [ ]:
df=df[["G1","G2","G3","studytime","failures","absences"]]
predict="G3"
X= np.array(df.drop([predict], axis=1))
Y=np.array(df[predict])

best = 0
for _ in range(10000):
    x_train, x_test, y_train, y_test=train_test_split(X,Y,test_size=0.1)
    linear=linear_model.LinearRegression()
    linear.fit(x_train,y_train)
    accuracy=linear.score(x_test,y_test)
    if accuracy>best:
        with open("Studentmodel.pickle","wb") as f:
            pickle.dump(linear,f)
pickle_in = open("Studentmodel.pickle", "rb")
linear = pickle.load(pickle_in)
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.1)
accuracy = linear.score(x_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.7763345208251612

In [ ]:
print("Co-efficient: \n", linear.coef_)
print("Intercept: \n", linear.intercept_)
predictions= linear.predict(x_test)

print("Actual Value\t\tGiven Input\t\tPredicted Value")
for x in range(len(predictions)):
    print("{}\t\t{}\t\t{:.5f}".format(y_test[x], x_test[x], predictions[x]))

Co-efficient:
 [ 0.1655722   0.95369015 -0.158895   -0.40204733  0.03643459]
Intercept:
 -1.329610438230734
Actual Value		Given Input		Predicted Value
6		[5 5 2 0 4]		4.09465
16		[17 16  2  0  0]		16.42637
15		[16 15  2  0 10]		15.67145
11		[12 12  2  0 12]		12.22096
10		[9 9 2 0 4]		8.57170
8		[ 9  8  2  0 10]		7.83662
5		[8 6 2 2 2]		4.66809
12		[12 12  1  0  8]		12.23412
10		[10  9  3  0  2]		8.50551
10		[11 11  1  1  6]		10.63994
20		[19 19  4  0  4]		19.44653
9		[10  9  3  0  2]		8.50551
14		[12 13  1  1  6]		12.71289
16		[14 16  3  0  0]		15.77076
15		[16 15  2  0 11]		15.70789
14		[15 14  2  0  8]		14.47932
10		[ 7 10  4  1  2]		8.40154
9		[8 9 1 0 5]		8.60146
0		[10  9  4  0  0]		8.27374
8		[6 8 1 1 0]		6.73240
18		[18 18  1  0  6]		18.87682
10		[9 9 2 0 6]		8.64457
8		[8 9 1 0 0]		8.41928
16		[16 15  3  0  9]		15.47612
0		[5 0 1 3 0]		-1.86679
9		[10  9  3  1 28]		9.05076
15		[17 15  1  0  2]		15.70444
12		[14 12  1  0  3]		12.38309
10		[8 9 2 0 8]		8.55187
10		[ 8 10  2  0  4]		9.35982
15		[15 15  2  0  0]		15.14153
12		[ 8 10  2  0  0]		9.21408
11		[12 10  2  0  2]		9.94924
7		[ 9  8  2  1 16]		7.65318
13		[13 14  1  0  0]		14.01560
17		[16 17  2  0  0]		17.21449
18		[18 18  1  1 24]		19.13060
7		[5 8 2 3 0]		5.60384
5		[ 5  5  2  0 12]		4.38613
11		[11 11  2  0 12]		11.10170